-- Criação do Schema Gold (DW)
CREATE SCHEMA IF NOT EXISTS dw;

-- 1. Dimensões (Sem alterações)
CREATE TABLE IF NOT EXISTS dw.DIM_USR (
    SRK_USR INTEGER PRIMARY KEY, -- Igual ao user_id original
    AGE_USR INTEGER,
    GEN_USR VARCHAR(50),
    CTR_USR VARCHAR(100),
    URB_RRL VARCHAR(50),
    EDU_LVL VARCHAR(100),
    EMP_STS VARCHAR(100),
    INC_LVL VARCHAR(50),
    REL_STS VARCHAR(100),
    HAS_CHD BOOLEAN
);

CREATE TABLE IF NOT EXISTS dw.DIM_ITR (
    SRK_ITR INTEGER PRIMARY KEY,
    CNT_TYP_PRF VARCHAR(100),
    CNT_TME_PRF VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS dw.DIM_CNT (
    SRK_CNT INTEGER PRIMARY KEY,
    APP_NME VARCHAR(100),
    ACC_CRT_YAR INTEGER,
    LST_LOG_DTE DATE,
    SUB_STS VARCHAR(50),
    USE_PRM_FTR BOOLEAN,
    PRV_LVL VARCHAR(50),
    TWO_FAC_AUT BOOLEAN,
    BIO_LOG_USE BOOLEAN
);

CREATE TABLE IF NOT EXISTS dw.DIM_ETL_VDA (
    SRK_ETL_VDA INTEGER PRIMARY KEY,
    EXE_HRS_WEK NUMERIC,
    SLP_HRS_NGT NUMERIC,
    DIT_QLT VARCHAR(50),
    BDY_MAS_IDX NUMERIC,
    BLD_PRS_SYS INTEGER,
    BLD_PRS_DIA INTEGER,
    DLY_STP_CNT INTEGER,
    STR_SCR INTEGER,
    HPN_SCR INTEGER,
    SMK_FLG BOOLEAN,
    ALC_FRQ VARCHAR(50),
    WRK_HRS_WEK NUMERIC,
    HOB_CNT INTEGER,
    SOC_EVT_MTH INTEGER,
    BKS_RED_YAR INTEGER,
    VOL_HRS_MTH NUMERIC,
    TRV_FRQ_YAR INTEGER
);

-- 2. Fatos (Atualizadas com SRK Própria)

-- Fato Ads Performance
CREATE TABLE IF NOT EXISTS dw.FT_ADS_PRF (
    SRK_ADS INTEGER PRIMARY KEY, -- Nova chave da Fato
    SRK_USR INTEGER,
    SRK_ETL_VDA INTEGER,
    SRK_CNT INTEGER,
    SRK_ITR INTEGER,
    ADS_VIW_DIA NUMERIC,
    ADS_CLK_DIA NUMERIC,
    CONSTRAINT fk_ads_usr FOREIGN KEY (SRK_USR) REFERENCES dw.DIM_USR (SRK_USR),
    CONSTRAINT fk_ads_etl FOREIGN KEY (SRK_ETL_VDA) REFERENCES dw.DIM_ETL_VDA (SRK_ETL_VDA),
    CONSTRAINT fk_ads_cnt FOREIGN KEY (SRK_CNT) REFERENCES dw.DIM_CNT (SRK_CNT),
    CONSTRAINT fk_ads_itr FOREIGN KEY (SRK_ITR) REFERENCES dw.DIM_ITR (SRK_ITR)
);

-- Fato Engajamento App
CREATE TABLE IF NOT EXISTS dw.FT_ENG_APP (
    SRK_ENG INTEGER PRIMARY KEY, -- Nova chave da Fato
    SRK_USR INTEGER,
    SRK_ETL_VDA INTEGER,
    SRK_CNT INTEGER,
    SRK_ITR INTEGER,
    DLY_ACT_MIN NUMERIC,
    SES_DIA NUMERIC,
    AVG_SES_MIN NUMERIC,
    ENG_SCR NUMERIC,
    LIK_GVN_DIA NUMERIC,
    COM_WRT_DIA NUMERIC,
    PST_CRT_WEK NUMERIC,
    DMS_SNT_WEK NUMERIC,
    DMS_RCV_WEK NUMERIC,
    RLS_WCH_DIA NUMERIC,
    STR_VIW_DIA NUMERIC,
    TIM_FED_DIA NUMERIC,
    TIM_EXP_DIA NUMERIC,
    TIM_RLS_DIA NUMERIC,
    TIM_MSG_DIA NUMERIC,
    FOL_CNT INTEGER,
    FLW_CNT INTEGER,
    LNK_ACC_CNT INTEGER,
    NTF_RSP_RAT NUMERIC,
    CONSTRAINT fk_eng_usr FOREIGN KEY (SRK_USR) REFERENCES dw.DIM_USR (SRK_USR),
    CONSTRAINT fk_eng_etl FOREIGN KEY (SRK_ETL_VDA) REFERENCES dw.DIM_ETL_VDA (SRK_ETL_VDA),
    CONSTRAINT fk_eng_cnt FOREIGN KEY (SRK_CNT) REFERENCES dw.DIM_CNT (SRK_CNT),
    CONSTRAINT fk_eng_itr FOREIGN KEY (SRK_ITR) REFERENCES dw.DIM_ITR (SRK_ITR)
);